version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - MONGODB_URI=mongodb+srv://ashwanikumar13628:Ashwani151717@cluster0.tgfgv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your-secret-key-change-in-production
      - CORS_ORIGIN=http://localhost:3000
      - CLOUDINARY_CLOUD_NAME=dn2bkta45
      - CLOUDINARY_API_KEY=892636761354991
      - CLOUDINARY_API_SECRET=luPdrJkWF6Z3Rm93PVOrPASax64
      # Redis configuration (using local Docker Redis)
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:
